name: Waka Readme

on:
  workflow_dispatch:
  workflow_run: 
    workflows: ["Profile CI"]
    types: [requested]
#     branches:
#       - 'origin/**'
    
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          TIME_RANGE: last_30_days
          BLOCKS: ⣀⣄⣿
          SHOW_TIME: false
          SHOW_MASKED_TIME: false
          LANG_COUNT: 7
          SECTION_NAME: Qin
          CODE_LANG: css
